SCR_MissionHeaderCampaign {
 World "{1ED5F233A4ED0062}Worlds/ArlandPVELobby.ent"
 m_sName "test gngngn"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}